import { _electron as electron } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root = process.cwd();
const artifacts = path.join(root,'artifacts');
await mkdir(artifacts,{recursive:true});
const dataDir=path.join(artifacts,'electron-test-profile');
await mkdir(dataDir,{recursive:true});
await writeFile(path.join(dataDir,'settings.json'),JSON.stringify({cwd:root}));
const env={...process.env,CODEX_DESK_TEST:'1',CODEX_DESK_DATA_DIR:dataDir};
delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({...(process.env.CODEX_DESK_PACKAGED ? {executablePath:process.env.CODEX_DESK_PACKAGED,args:[]} : {args:['.']}),cwd:root,env,timeout:30000});
const errors=[];
try {
 const page=await app.firstWindow();
 page.on('pageerror',e=>errors.push(e.message));
 await page.waitForFunction(()=>Boolean(window.codex),null,{timeout:15000});
 await page.waitForFunction(()=>{const model=document.querySelector('[role="combobox"][aria-label="Модель"]');return model && !model.disabled;},null,{timeout:30000});
 const config=await page.evaluate(async()=>{const boot=await window.codex.start();return {model:boot.config.model,effort:boot.config.model_reasoning_effort,modelCount:boot.models.length,exe:boot.executable};});
 assert.ok(config.modelCount>0);
 console.log('Real Electron + Codex bootstrap:',JSON.stringify(config));
 const selectors=await page.getByRole('combobox').evaluateAll(nodes=>nodes.map(n=>({label:n.getAttribute('aria-label'),value:n.getAttribute('data-value'),text:n.textContent})));
 console.log('Selectors:',JSON.stringify(selectors));
 const textarea=page.locator('textarea').first();
 await textarea.fill('Проверка удобного ввода');
 assert.equal(await textarea.inputValue(),'Проверка удобного ввода');
 const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
 await textarea.evaluate((el,dataUrl)=>{const data=new DataTransfer();const bytes=Uint8Array.from(atob(dataUrl.split(',')[1]),c=>c.charCodeAt(0));data.items.add(new File([bytes],'clipboard.png',{type:'image/png'}));el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},image);
 await page.waitForFunction(()=>document.querySelector('img[src^="data:image/png"]'));
 const persisted=await page.evaluate(dataUrl=>window.codex.saveImages([{name:'clipboard.png',dataUrl}]),image);
 assert.ok(persisted[0].path.endsWith('.png'));
 await page.getByRole('button',{name:/^Обновить диалоги /}).first().waitFor();
 await page.waitForFunction(()=>{const refresh=document.querySelector('.folder-refresh');return refresh && !refresh.disabled;});
 await page.screenshot({path:path.join(artifacts,'desktop.png'),fullPage:true});
 console.log('Buttons:',JSON.stringify(await page.getByRole('button').allTextContents()));
 assert.deepEqual(errors,[]);
 console.log('PASS: real window, inherited model/effort, pasted image preview, native image storage, no renderer errors.');
} finally { await app.close(); }
