import type { SetupBridge } from './setup-types';
import type { MemoryRulesBridge } from './memory-rules-types';
export type Access = 'inherited' | 'auto' | 'read-only' | 'workspace-write' | 'danger-full-access';
export type AgentProvider = 'codex' | 'claude';
export type AgentCapabilities = { compact: boolean; steer: boolean; terminal: boolean; mcp: boolean; archive: boolean; usage?: boolean };
export type AgentDetails = { commands: { name: string; description: string; builtin: boolean }[]; agents: { name: string; description: string }[]; mcpServers: { name: string; status: 'connected' | 'failed' | 'needs-auth' | 'pending' | 'disabled'; error?: string; scope?: string }[] | null; mcpError?: string };
export type UsageWindow = { key: string; label: string; utilization: number | null; resetsAt: string | null };
export type UsageLimits = { available: boolean; subscription?: string | null; windows: UsageWindow[]; updatedAt?: string; message?: string };
export type ClaudeAuthStatus = { loggedIn: boolean; authMethod?: string; email?: string; subscriptionType?: string; apiProvider?: string; configDirectory?: string; loginInProgress: boolean };
export type ClaudeTokenInfo = { configured: boolean; savedAt?: string; encryptionAvailable: boolean; error?: string; restarted?: number; busy?: number };
export type Settings = { cwd?: string; model?: string; effort?: string; access?: Access; executable?: string; provider?: AgentProvider };
/** Where a tab's effective value came from: restored tab snapshot, saved agent defaults, CLI configuration, a built-in default, or the user's choice in this tab. */
export type SettingSource = 'tab' | 'saved' | 'cli' | 'default' | 'selected';
export type SettingSources = { model: SettingSource; effort: SettingSource; access: SettingSource };
export type BridgeEvent = { type: 'notification' | 'serverRequest' | 'status' | 'diagnostic' | 'terminal' | 'mcp' | 'auth'; data: any };
export type Attachment = { name: string; dataUrl: string; path?: string };
export type ComposerFiles = { images: Attachment[]; paths: string[]; message?: string };
export type QueuedMessage = { id: string; text: string; attachments: Attachment[]; state?: 'waiting' | 'uncertain' };
export type MessageQueueState = { items: QueuedMessage[]; paused: boolean; reason?: string; threadId?: string; cwd?: string };
export type PreservedDraft = { text: string; attachments: Attachment[] };
export type PendingMessage = { threadId: string; clientUserMessageId: string; kind: 'start' | 'steer'; text: string; attachments: Attachment[] };
export type ScrollAnchor = { itemId: string; offset: number };
export type NotificationKind = 'completed' | 'question' | 'approval' | 'error';
export type NotificationPreferences = { enabled: boolean; sound: boolean; completed: boolean; question: boolean; approval: boolean; error: boolean };
export type NotificationSettingsInfo = { settings: NotificationPreferences; supported: boolean };
export type SessionAttentionEvent = { kind: NotificationKind; eventId: string };
export type Item = { id: string; type: string; turnId?: string; complete?: boolean; [key: string]: any };
// Internal timestamps are milliseconds; App Server turn timestamps are seconds.
export type TurnWork = { id: string; status: string; startedAt?: number; completedAt?: number; durationMs?: number; answerStartedAt?: number };
export type Thread = { id: string; name?: string; preview?: string; cwd?: string; updatedAt?: number; turns?: any[]; provider?: AgentProvider; [key: string]: any };
export type ThreadAction = 'rename' | 'archive' | 'delete' | 'restore' | 'fork';
export type ArchivedThreadPage = { thread: Thread; items: Item[]; turns: any[]; nextCursor: string | null };
export type Request = { id: number | string; method: string; params: any };
export type Model = { id: string; model: string; displayName: string; hidden?: boolean; isDefault?: boolean; defaultReasoningEffort: string; supportedReasoningEfforts: { reasoningEffort: string; description: string }[]; inputModalities?: string[] };

export type SessionInfo = { id: string; cwd: string; provider?: AgentProvider };
export type WorktreeInfo = { path: string; branch: string; created: boolean; root: string };
export type WorktreeEntry = { path: string; branch: string | null; head: string | null; detached: boolean; bare: boolean; main: boolean; current: boolean; dirty: boolean | null; ahead: number | null; behind: number | null };
export type WorktreeSummary = { root: string; mainBranch: string | null; mainPath: string | null; worktrees: WorktreeEntry[] };
export type WorktreeMergePreview = { branch: string; target: string; mainPath: string; worktreePath: string; commits: { hash: string; subject: string }[]; stat: string; ahead: number | null; behind: number | null; mainDirty: boolean; worktreeDirty: boolean; blocked: string | null };
export type UpdateTabSnapshot = { sessionId?: string; thread?: Thread; archivedThread?: Thread; settings?: Settings; draft: string; attachments: Attachment[]; preservedDraft?: PreservedDraft; queue?: MessageQueueState; scrollTop?: number; scrollAnchor?: ScrollAnchor; pinned?: boolean; pendingMessage?: PendingMessage };
export type UpdateSnapshot = { version: 1; activeIndex: number; tabs: UpdateTabSnapshot[] };
export type RestoredTab = SessionInfo & { thread?: Thread; archivedThread?: Thread; settings?: Settings; draft?: string; attachments?: Attachment[]; preservedDraft?: PreservedDraft; queue?: MessageQueueState; scrollTop?: number; scrollAnchor?: ScrollAnchor; pinned?: boolean; pendingMessage?: PendingMessage };
export type UpdateStatus = { state: 'awaiting' | 'waiting' | 'manual' | 'preparing' | 'error'; message?: string };
export type WorkspaceInfo = { projects: string[]; sessions: SessionInfo[]; restore?: { activeIndex: number; tabs: RestoredTab[]; kind?: 'workspace' | 'update' } };
export type AppUpdateStatus = {
  currentVersion: string;
  channel: 'stable' | 'nightly' | 'development';
  enabled: boolean;
  supported: boolean;
  phase: 'idle' | 'checking' | 'available' | 'up-to-date' | 'error' | 'disabled';
  checkedAt?: string;
  latestVersion?: string;
  releaseUrl?: string;
  downloadUrl?: string;
  releaseNotes?: string;
  error?: string;
  skippedVersion?: string;
};
export type BuildInfo = { channel: 'stable' | 'nightly' | 'development'; version: string; buildId?: string; builtAt?: string };
export type DiagnosticsStatus = { enabled: boolean; directory: string | null; error?: string };
export type RendererErrorReport = { kind: 'error' | 'unhandledrejection' | 'react'; name?: string; message?: string; stack?: string; componentStack?: string };
export type ProjectFile = { name: string; path: string; type: 'directory' | 'file' | 'link' };
export type ProjectFilePage = { path: string; entries: ProjectFile[]; nextCursor: number | null };
export type ProjectSearchPage = { files: { path: string; name: string }[]; nextCursor: string | null; truncated?: boolean };
export type ProjectFilePreview = { path: string; kind: 'text' | 'markdown' | 'image' | 'unsupported'; text?: string; dataUrl?: string; language?: string; truncated?: boolean; message?: string };
export type HistoryTarget = { cwd: string; provider: AgentProvider; thread: Thread; itemId: string; turnId?: string; snippet?: string; excerpt?: string; archived?: boolean };
export type HistorySearchPage = { matches: HistoryTarget[]; nextCursor: string | null; scannedThreads: number; scannedPages: number; warnings?: string[] };
export type Bookmark = { id: string; provider: AgentProvider; cwd: string; threadId: string; itemId: string; turnId?: string; threadName: string; excerpt: string; label: string; createdAt: string; updatedAt: string; archived?: boolean };
export type GitArea = 'staged' | 'unstaged' | 'untracked';
export type GitEntry = { path: string; originalPath?: string; status: string; indexStatus: string; worktreeStatus: string; staged: boolean; unstaged: boolean; untracked: boolean; conflicted: boolean; submodule?: boolean };
export type GitStatus = { available: boolean; reason?: 'not-repository' | 'git-unavailable' | 'bare'; root?: string; branch?: string; detached?: boolean; unborn?: boolean; head?: string; entries: GitEntry[]; truncated?: boolean; message?: string };
export type GitDiff = { path: string; area: GitArea; diff: string; binary?: boolean; truncated?: boolean; message?: string };
export type GitRollbackHunk = { index: number; header: string; oldStart: number; oldCount: number; newStart: number; newCount: number; removed: number; added: number; excerpt: string };
export type GitRollbackPreview = { previewId: string; path: string; diff: string; binary?: boolean; truncated?: boolean; message?: string; expiresAt: string; operation: 'restore' | 'undo'; hunks?: GitRollbackHunk[] };
export type GitRollbackRecord = { undoId: string; path: string; createdAt: string };
export type McpServerSummary = { name: string; transport: 'http' | 'stdio'; address: string; enabled: boolean; headerNames: string[]; envNames: string[] };
export type McpConfigInfo = { configPath: string; servers: McpServerSummary[] };
export type McpImportPreview = { previewId: string; configPath: string; servers: (McpServerSummary & { exists: boolean })[]; conflicts: string[] };
export type McpSaveResult = { configPath: string; backupPath: string | null; servers: string[]; message?: string };
export type McpConnectionReport = { servers: { name: string; authStatus: string; status: string; toolCount: number }[]; message?: string };
export interface CodexBridge {
  start(options?: { cwd?: string }): Promise<{ initialize: any; models: Model[]; account: any; config: any; cwd: string; executable: string; provider?: AgentProvider; capabilities?: AgentCapabilities; cliVersion?: string }>;
  request(method: string, params?: any): Promise<any>;
  respond(id: number | string, result: any): Promise<void>;
  chooseDirectory(): Promise<string | null>;
  saveImages(images: Attachment[]): Promise<Attachment[]>;
  chooseComposerFiles(options?: { imageSlots?: number; imagesSupported?: boolean }): Promise<ComposerFiles | null>;
  getPathForFile(file: File): string;
  readClipboardFiles(options?: { imageSlots?: number; imagesSupported?: boolean }): Promise<ComposerFiles | null>;
  readAttachment(path: string): Promise<string | null>;
  onEvent(listener: (event: BridgeEvent) => void): () => void;
  getSettings(): Promise<Settings>;
  setSettings(settings: Partial<Settings>): Promise<void>;
  openPath(path: string): Promise<void>;
  showPathMenu(path: string, options?: { askCodex?: boolean }): Promise<void | { action: 'askCodex'; path: string }>;
  listFiles(relativePath?: string, cursor?: number): Promise<ProjectFilePage>;
  searchProjectFiles(options: { query: string; cursor?: string }): Promise<ProjectSearchPage>;
  readProjectFile(options: { path: string }): Promise<ProjectFilePreview>;
  getGitStatus(): Promise<GitStatus>;
  getGitDiff(options: { path: string; area: GitArea }): Promise<GitDiff>;
  previewGitRollback(options: { path: string }): Promise<GitRollbackPreview>;
  applyGitRollback(options: { previewId: string; hunks?: number[] }): Promise<GitRollbackRecord>;
  listGitRollbacks(): Promise<GitRollbackRecord[]>;
  previewUndoGitRollback(options: { undoId: string }): Promise<GitRollbackPreview>;
  undoGitRollback(options: { previewId: string }): Promise<{ path: string }>;
  chooseExecutable(): Promise<string | null>;
  openTerminal(options: { threadId: string; model: string; effort: string; access: Access }): Promise<{ threadId: string }>;
  getClaudeAuthStatus(): Promise<ClaudeAuthStatus>;
  loginClaude(): Promise<{ started: true }>;
  getClaudeToken(): Promise<ClaudeTokenInfo>;
  setClaudeToken(token: string): Promise<ClaudeTokenInfo>;
  clearClaudeToken(): Promise<ClaudeTokenInfo>;
  setupClaudeToken(): Promise<{ started: true }>;
  getMcpConfig(): Promise<McpConfigInfo>;
  previewMcpImport(text: string): Promise<McpImportPreview>;
  saveMcpImport(options: { previewId: string; replaceExisting: boolean }): Promise<McpSaveResult>;
  reloadMcp(): Promise<{ status: 'applied' | 'deferred'; message: string }>;
  checkMcp(): Promise<McpConnectionReport>;
}
export interface WorkspaceBridge extends CodexBridge {
  setup?: SetupBridge;
  memoryRules?: MemoryRulesBridge;
  searchHistory(options: { query: string; cwd: string; provider: AgentProvider | 'all'; cursor?: string }): Promise<HistorySearchPage>;
  resolveHistoryTarget(options: { cwd: string; provider: AgentProvider; threadId: string }): Promise<Thread>;
  listBookmarks(options?: { cwd?: string; provider?: AgentProvider | 'all' }): Promise<Bookmark[]>;
  saveBookmark(bookmark: Omit<Bookmark, 'id' | 'createdAt' | 'updatedAt' | 'label'> & { id?: string; label?: string }): Promise<Bookmark>;
  removeBookmark(id: string): Promise<{ removed: boolean }>;
  getNotificationSettings(): Promise<NotificationSettingsInfo>;
  setNotificationSettings(settings: Partial<NotificationPreferences>): Promise<NotificationSettingsInfo>;
  setNotificationContext(context: { activeSessionId?: string }): Promise<void>;
  notifySession(event: SessionAttentionEvent & { sessionId: string; title: string }): Promise<void>;
  onNotificationActivated(listener: (event: { sessionId: string }) => void): () => void;
  getWindowFocus(): Promise<boolean>;
  onWindowFocus(listener: (focused: boolean) => void): () => void;
  getBuildInfo(): Promise<BuildInfo>;
  getAppUpdateStatus(): Promise<AppUpdateStatus>;
  checkAppUpdates(): Promise<AppUpdateStatus>;
  setAppUpdatePreferences(patch: { enabled?: boolean; skippedVersion?: string | null }): Promise<AppUpdateStatus>;
  openAppUpdateDownload(): Promise<void>;
  onAppUpdateStatus(listener: (status: AppUpdateStatus) => void): () => void;
  getDiagnosticsStatus(): Promise<DiagnosticsStatus>;
  exportDiagnostics(): Promise<{ canceled: boolean; path?: string }>;
  exportConversation(file: { filename: string; content: string; format: 'markdown' | 'html' }): Promise<{ canceled: boolean; path?: string }>;
  openDiagnosticsFolder(): Promise<void>;
  reportRendererError(report: RendererErrorReport): void;
  getWorkspace(): Promise<WorkspaceInfo>;
  saveWorkspaceState(snapshot: UpdateSnapshot): Promise<void>;
  onWorkspaceSave(listener: (request: { requestId: string }) => void): () => void;
  completeWorkspaceSave(result: { requestId: string; snapshot?: UpdateSnapshot }): Promise<void>;
  onUpdatePrepare(listener: (request: { requestId: string }) => void): () => void;
  onUpdateStatus(listener: (status: UpdateStatus) => void): () => void;
  getUpdateStatus(): Promise<UpdateStatus | null>;
  decideUpdate(decision: 'close' | 'later'): Promise<UpdateStatus>;
  completeUpdatePrepare(result: { requestId: string; snapshot?: UpdateSnapshot; defer?: boolean }): Promise<void>;
  completeUpdateRestore(): Promise<void>;
  listProjectThreads(cwd: string, cursor?: string): Promise<{ data: Thread[]; nextCursor: string | null }>;
  searchThreads(options: { query: string; archived: boolean; cursor?: string }): Promise<{ data: Thread[]; nextCursor: string | null }>;
  listArchivedThreads(cursor?: string): Promise<{ data: Thread[]; nextCursor: string | null }>;
  readArchivedThread(options: { threadId: string; cursor?: string }): Promise<ArchivedThreadPage>;
  openArchivedPath(options: { threadId: string; target: string; menu?: boolean }): Promise<void>;
  manageThread(options: { action: ThreadAction; threadId: string; cwd: string; name?: string }): Promise<{ thread?: Thread; affectedThreadIds?: string[] }>;
  createSession(options?: { cwd?: string; fromSessionId?: string; settings?: Settings; provider?: AgentProvider }): Promise<SessionInfo | null>;
  createWorktreeSession?(options: { cwd: string; fromSessionId?: string; name: string; provider?: AgentProvider }): Promise<(SessionInfo & { worktree: WorktreeInfo }) | null>;
  listWorktrees?(cwd: string): Promise<WorktreeSummary>;
  previewWorktreeMerge?(cwd: string): Promise<WorktreeMergePreview>;
  mergeWorktree?(cwd: string): Promise<{ branch: string; target: string; mainPath: string; before: string; after: string; commits: number }>;
  removeWorktree?(cwd: string, options?: { force?: boolean; deleteBranch?: boolean }): Promise<{ path: string; branch: string | null; branchDeleted: boolean }>;
  closeSession(id: string): Promise<void>;
  closeProject(cwd: string, options?: { force?: boolean }): Promise<{ projects: string[]; closedSessionIds: string[] }>;
  forSession(id: string): CodexBridge;
}
declare global {
  interface Window { codex: WorkspaceBridge; }
}
